<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DOBLN3AU" failures="0" tests="5" name="com.ninja.qa.TestPages.HomePageTest" time="36.567" errors="1" timestamp="2023-10-10T11:45:11 IST" skipped="0">
  <testcase classname="com.ninja.qa.TestPages.HomePageTest" name="generateReports" time="8.416">
    <error message="Failed to open file:/C:/Users/sonal/Workspace2-git/NinjaDemo-POMFramework/reportpom.html. Error message: The system cannot find the file specified.
" type="java.io.IOException">
      <![CDATA[java.io.IOException: Failed to open file:/C:/Users/sonal/Workspace2-git/NinjaDemo-POMFramework/reportpom.html. Error message: The system cannot find the file specified.

at java.desktop/sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:115)
at java.desktop/sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:101)
at java.desktop/java.awt.Desktop.browse(Desktop.java:526)
at com.ninja.qa.Base.TestBase.generateReports(TestBase.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:404)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- generateReports -->
  <system-out/>
  <testcase classname="com.ninja.qa.TestPages.HomePageTest" name="testTitle" time="6.600"/>
  <system-out/>
  <testcase classname="com.ninja.qa.TestPages.HomePageTest" name="testRegisterLink" time="7.059"/>
  <system-out/>
  <testcase classname="com.ninja.qa.TestPages.HomePageTest" name="testLoginLink" time="11.474"/>
  <system-out/>
  <testcase classname="com.ninja.qa.TestPages.HomePageTest" name="testMacLink" time="3.018"/>
  <system-out/>
</testsuite> <!-- com.ninja.qa.TestPages.HomePageTest -->
